// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace repro.Model.CompiledModels
{
    public partial class LanguageDbContextModel
    {
        private LanguageDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("54c4a933-a2ac-46a0-98a0-e70b35dba3d2"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var sentence = SentenceEntityType.Create(this);

            SentenceEntityType.CreateAnnotations(sentence);

            AddAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");
        }
    }
}
