// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Model;
using repro.Model.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(LanguageDbContext), typeof(LanguageDbContextModel))]
